export default {
	PROFILE_RECEIVED: 'PROFILE_RECEIVED',
	COMMENT_CREATED: 'COMMENT_CREATED',
	COMMENT_RECEIVED: 'COMMENT_RECEIVED',
	ZONE_SELECTED: 'ZONE_SELECTED',
	ZONES_RECEIVED: 'ZONES_RECEIVED',
	ZONE_CREATED: 'ZONE_CREATED',
	CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
	LOG_OUT: 'LOG_OUT'
}